### ISSUE TITLE
Kurs mittels Passwort beitreten

### ISSUE THREAD

**Issue by klingebiel** [Student-Management-System/StudentMgmt-Client#2]
Ein Kursteilnehmer muss einem, mittels Kurspasswort geschütztem Kurs, beitreten können wenn der Kursteilnehmer über das Kurspasswort verfügt.

**Comment by Elscha** [comment]
**Anmerkung:** Passwortschutz für Kurse ist optional (Kurse können geschützt werden, müssen aber nicht zwingend geschützt werden).
